---
- name: install packages
  ansible.builtin.package:
    name:  encfs
    state: present
  become: true

- name: create sudoers files for {{user}}
  ansible.builtin.lineinfile:
    path: "/etc/sudoers.d/{{user}}"
    line: "{{item}}"
    state: present
    mode:  0600
    create: yes
  with_items:
  - "{{user}} ALL=(ALL) NOPASSWD: /usr/bin/encfs -u {{mediaOtherShare}}"
  - "{{user}} ALL=(ALL) NOPASSWD: /usr/bin/encfs -S --public {{mediaOtherDir}} {{mediaOtherShare}}"
  become: true

- name: install mount/umount script
  ansible.builtin.template:
    src:  other
    dest: "{{userDir}}/.local/bin"
    mode: 0754

- name: create some aliases for bash
  ansible.builtin.blockinfile:
    path: "{{userDir}}/.bashrc"
    block: |
      alias voff='other  off'
      alias von='other   on'
      alias vstat='other stat'
    insertafter: EOF
    marker: "##### {mark} inserted by ansible role {{ansible_role_name}}"

- name: create directory
  ansible.builtin.file:
    path:  "{{mediaOtherShare}}"
    state: directory

- name: configure exports
  ansible.builtin.template:
    src:   othershare.exports
    dest:  /etc/exports.d/
    owner: root
    group: root
    mode:  0644
  become: true
  notify: reload exports

