---
- name: run generic archive recover task
  include_role:
    name:       archive
    tasks_from: restore

- name: look for extension list
  ansible.builtin.stat:
    path: "{{extList}}"
  register: st
  
- block:
  - name: load extensions list from backup
    ansible.builtin.include_vars:
      file: "{{extList}}"
  - name: install extensions
    ansible.builtin.command: "code --install-extension {{item}}"
    register: result
    changed_when: '"successfully installed" in result.stdout'
    with_items: "{{extensions}}"
  - name: remove extention list
    ansible.builtin.file:
      path: "{{extList}}"
      state: absent
  when: st.stat.exists

