---
- name: create temp dir
  ansible.builtin.file:
    path: "{{tempDir}}"
    state: directory

- name: make the files
  ansible.builtin.shell:
    cmd: "dconf dump {{item.path}} > {{tempDir}}/{{item.file}}"
  with_items: "{{files}}"

#- name: grab gnome-shell.css
#  ansible.builtin.copy:
#    src:  "{{gnomeShellCss}}"
#    dest: "{{tempDir}}/"

- name: create the archive
  include_role:
    name:       archive
    tasks_from: create

- name: remove temp dir
  ansible.builtin.file:
    path: "{{tempDir}}"
    state: absent
