---
- name: install
  aur:
    name:  google-chrome
    state: present

- name: create config file
  ansible.builtin.copy:
    src:  chrome-flags.conf
    dest: "{{userDir}}/.config"

#### Extensions not restored
# Remote Transmission ++
# ublock my filters
# CAD list of expressions
# new tab redirect
# location guard fixed location
