---
- name: install ext pack installer script
  ansible.builtin.copy:
    src:  install-vbox-extpack.sh
    dest: /usr/bin/
    mode: 0755
  become: true

- name: add install/update hook
  ansible.builtin.template:
    src:  custom-virtualbox-post.hook
    dest: /usr/share/libalpm/hooks
  become: true

- name: install packages
  ansible.builtin.package:
    name: "{{item}}"
    state: present
  with_items:
  - virtualbox
  - "linux{{ansible_kernel.split('.')[0] }}{{ ansible_kernel.split('.')[1]}}-virtualbox-host-modules"
  - virtualbox-guest-iso
  become: true

- name: add user to group
  ansible.builtin.user:
    name:   "{{user}}"
    groups: vboxusers
    append: yes
  become: true

- name: set default machine directory
  ansible.builtin.command:
    cmd: vboxmanage setproperty machinefolder {{vboxDir}}
